tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
  - before:
      source venv/bin/activate

ports:
  - port: 5000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - vscode-icons-team.vscode-icons
    - ritwickdey.liveserver
    - dracula-theme.theme-dracula
    - enkia.tokyo-night
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
